name: google_cloud_metagenomics
channels:
  - bioconda
  - conda-forge
  - hcc
  - anaconda-platform
  - defaults
dependencies:
  - snakemake-minimal =5.3.1
  - python =3.6
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =2.2.3
  - graphviz =2.38.0
  - bcftools =1.9
  - samtools =1.9
  - bwa =0.7.17
  - pysam =0.15.0
  - cutadapt =1.18
  - aspera-cli =3.7.7
  - kubectl
